export const DIRECTION = {
	IDLE: 0,
	LEFT: 1,
	RIGHT: 2,
	UP: 3,
	DOWN: 4,
};

export const ORIENTATION = {
	VERTICAL: 'ORIENTATION.VERTICAL',
	HORIZONTAL: 'ORIENTATION.HORIZONTAL',
};

export const POSITION = {
	LEFT: 'POSITION.LEFT',
	RIGHT: 'POSITION.RIGHT',
	TOP: 'POSITION.TOP',
	BOTTOM: 'POSITION.BOTTOM',
};

export const GAME = {
	PADDLE_ONE: 'GAME.PADDLE_ONE',
	PADDLE_TWO: 'GAME.PADDLE_TWO',
};
